<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.162" timestamp="2025-03-31T00:55:37.863838-03:00" hostname="ubuntu24-B550M-AORUS-ELITE"><testcase classname="" name="tests.models.test_caminhos" time="0.000"><error message="collection failure">ImportError while importing test module '/home/pedro-pm-dias/API_LOCAL/GitHub/UniBMark/tests/models/test_caminhos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/models/test_caminhos.py:7: in &lt;module&gt;
    from models.path_validator import PathValidator
E   ModuleNotFoundError: No module named 'models'</error></testcase></testsuite></testsuites>